exp_name: 'cityscapes2'
lr: 0.0001
wd: 0.00001

epochs: 1000
batch_size: 4
batch_accum: 8
patience: 30

img_size: 512
img_rgb: True

train_img_dir: '../../../cityscapes_data/leftImg8bit/my_train'
val_img_dir: '../../../cityscapes_data/leftImg8bit/my_val'
test_img_dir: 

train_mask_dir: '../../../cityscapes_data/gtFine/my_train'
val_mask_dir: '../../../cityscapes_data/gtFine/my_val'
test_mask_dir: 

model_save_dir: 'saved_weight'
model_load_path: 

num_classes: 12
mixed_precision: True