exp_name: 'RTN_Feb_3'
lr: 0.0001
epochs: 500
batch_size: 16
batch_accum: 16

img_folder_train: '../../SyntheticData/data/RectTickData/train_imgs'
label_path_train: '../../SyntheticData/data/RectTickData/train_labels.json'
img_folder_val: '../../SyntheticData/data/RectTickData/val_imgs'
label_path_val: '../../SyntheticData/data/RectTickData/val_labels.json'